server.port=8200


spring.rabbitmq.username=${TANZU_RABBITMQ_USER}
spring.rabbitmq.password=${TANZU_RABBITMQ_PASSWORD}

#spring.ai.ollama.chat.options.model=gemma3
spring.ai.ollama.chat.options.model=llama3
#spring.ai.ollama.chat.options.model=llama3.2

# 1. Force all consumers (queues) to use RabbitMQ Streams container
spring.cloud.stream.rabbit.default.consumer.containerType=stream
#spring.cloud.stream.rabbit.default.producer.producerType=STREAM_SYNC

spring.ai.vectorstore.redis.initialize-schema=true

spring.cloud.function.definition=stockNewsAnalyzerProcessor;newsDomainContextSink;generateNews
spring.cloud.function.web.path=/functions
spring.cloud.function.web.mappings.stockNewAnalyzerProcessor.path=/functions/news
spring.cloud.function.web.mappings.stockNewAnalyzerProcessor.method=POST
spring.cloud.stream.http.POST=stockNewAnalyzerProcessor;ping
# For Inputs (Consuming data)
#spring.cloud.stream.function.bindings.stockNewsAnalyzerProcessor-in-0=input
#spring.cloud.stream.function.bindings.stockNewsAnalyzerProcessor-out-0=output
spring.cloud.stream.bindings.stockNewsAnalyzerProcessor-in-0.destination=stocks.news
spring.cloud.stream.bindings.stockNewsAnalyzerProcessor-in-0.group=sentiment-news-agent
spring.cloud.stream.bindings.stockNewsAnalyzerProcessor-out-0.destination=stocks.news.analysis
#spring.cloud.stream.bindings.output.destination=stocks.news.analysis


spring.cloud.stream.bindings.newsDomainContextSink-in-0.destination=stocks.news.context
spring.cloud.stream.bindings.newsDomainContextSink-in-0.group=newsDomainContextSink
spring.cloud.stream.rabbit.bindings.newsDomainContextSink-in-0.consumer.containerType=stream
#spring.cloud.stream.rabbit.bindings.newsDomainContextSink-out-0.producer.producerType=STREAM_SYNC

# News Generator

spring.cloud.stream.rabbit.bindings.generateNews-out-0.producer.producerType=AMQP
#spring.cloud.stream.bindings.generateNews-out-0.destination=${spring.cloud.stream.bindings.stockNewsAnalyzerProcessor-in-0.destination}.${spring.cloud.stream.bindings.stockNewsAnalyzerProcessor-in-0.group}
spring.cloud.stream.bindings.generateNews-out-0.destination=${spring.cloud.stream.bindings.stockNewsAnalyzerProcessor-in-0.destination}
#spring.cloud.stream.bindings.generateNews-out-0.destination=${spring.cloud.stream.bindings.output.destination}
spring.cloud.stream.bindings.generateNews-out-0.producer.contentType=application/json

# 5 seconds
spring.cloud.stream.bindings.generateNews-out-0.producer.poller.fixed-delay=5000


springdoc.swagger-ui.path=/swagger-ui.html
