rootProject.name = 'financial-trading-ai-agentic-showcase'
include ':components:trading-domain'
include ':components:server:gemfire:trader-functions'
include ':applications:batch:stock-daily-price-batch'
include ':applications:research-trader-agent'
include ':applications:sentiment-news-agent'
include ':applications:portfolio-agent'
include ':applications:api:stock-price-api'
include ':applications:mcp:portfolio-sql-analytics-mcp-server'
