server.port=8200
spring.cloud.function.definition=stockNewsAnalyzerProcessor;newsDomainContextSink;generateNews
spring.cloud.function.web.path=/functions
spring.cloud.function.web.mappings.stockNewAnalyzerProcessor.path=/functions/news
spring.cloud.function.web.mappings.stockNewAnalyzerProcessor.method=POST
spring.cloud.stream.http.POST=stockNewAnalyzerProcessor;ping
# For Inputs (Consuming data)
spring.cloud.stream.function.bindings.stockNewsAnalyzerProcessor-in-0=input
spring.cloud.stream.function.bindings.stockNewsAnalyzerProcessor-out-0=output
spring.cloud.stream.bindings.input.destination=stocks.news
spring.cloud.stream.bindings.input.group=sentiment-news-agent
spring.cloud.stream.bindings.output.destination=stocks.news.analysis


spring.cloud.stream.bindings.newsDomainContextSink-in-0.destination=stocks.news.context
spring.cloud.stream.bindings.newsDomainContextSink-in-0.group=newsDomainContextSink


# News Generator
spring.cloud.stream.bindings.generateNews-out-0.destination=${spring.cloud.stream.bindings.input.destination}

# 5 seconds
spring.cloud.stream.bindings.generateNews-out-0.producer.poller.fixed-delay=5000

springdoc.swagger-ui.path=/swagger-ui.html
