server.port=8200
spring.cloud.function.definition=stockNewAnalyzerProcessor
spring.cloud.function.web.path=/functions
spring.cloud.stream.http.POST=stockNewAnalyzerProcessor;ping
# For Inputs (Consuming data)
spring.cloud.stream.function.bindings.stockNewAnalyzerProcessor-in-0=input
spring.cloud.stream.function.bindings.stockNewAnalyzerProcessor-out-0=output
spring.cloud.stream.bindings.input.destination=stocks.news
spring.cloud.stream.bindings.input.group=processor

springdoc.swagger-ui.path=/swagger-ui.html

# For Outputs (Publishing data)
spring.cloud.stream.bindings.stockNewAnalyzerProcessor-out-0.destination=<topic_or_exchange_name>