server.port=8200
spring.cloud.function.definition=stockNewAnalyzerProcessor;newsDomainContextSink
spring.cloud.function.web.path=/functions
spring.cloud.function.web.mappings.stockNewAnalyzerProcessor.path=/functions/news
spring.cloud.function.web.mappings.stockNewAnalyzerProcessor.method=POST
spring.cloud.stream.http.POST=stockNewAnalyzerProcessor;ping
# For Inputs (Consuming data)
spring.cloud.stream.function.bindings.stockNewAnalyzerProcessor-in-0=input
spring.cloud.stream.function.bindings.stockNewAnalyzerProcessor-out-0=output
spring.cloud.stream.bindings.input.destination=stocks.news
spring.cloud.stream.bindings.input.group=processor


spring.cloud.stream.bindings.newsDomainContextSink-in-0.destination=stocks.news.context
spring.cloud.stream.bindings.newsDomainContextSink-in-0.group=newsDomainContextSink

springdoc.swagger-ui.path=/swagger-ui.html

# For Outputs (Publishing data)
spring.cloud.stream.bindings.stockNewAnalyzerProcessor-out-0.destination=<topic_or_exchange_name>