
stock.faker.exchange=NASDAQ
stock.faker.low-price=15.25
stock.faker.high-price=450.75
stock.faker.low-volume=1000
stock.faker.high-volume=500000
stock.faker.currency=USD

app.stock.api.service.stockUrl=http://localhost:9999/v1/stockprice/limit
app.stock.api.service.startupStockTicker=AAPL
spring.data.gemfire.pool.locators=localhost[10334]
spring.application.name=research-trader-agent-processor
server.port=8066

# 1. Force all consumers (queues) to use RabbitMQ Streams container
spring.cloud.stream.rabbit.default.consumer.containerType=stream
#spring.cloud.stream.rabbit.default.producer.producerType=STREAM_SYNC

spring.rabbitmq.username=${TANZU_RABBITMQ_USER}
spring.rabbitmq.password=${TANZU_RABBITMQ_PASSWORD}


#SuggestTradeAdviceFunction

spring.cloud.function.definition=suggestTradeAdviceProcessor;saveStockPriceMovingAverageSink
spring.cloud.function.web.path=/functions
spring.cloud.function.web.mappings.suggestTradeAdviceProcessor.path=/functions/news
spring.cloud.function.web.mappings.suggestTradeAdviceProcessor.method=POST
spring.cloud.stream.http.POST=suggestTradeAdviceProcessor

#saveStockPriceMovingAverageSink
spring.cloud.stream.bindings.saveStockPriceMovingAverageSink-in-0.destination=research-stock-price-moving-average
spring.cloud.stream.bindings.saveStockPriceMovingAverageSink-in-0.group=research-trader-agent
spring.cloud.function.web.mappings.saveStockPriceMovingAverageSink.path=/functions/stock/price/moving
spring.cloud.function.web.mappings.saveStockPriceMovingAverageSink.method=POST

# For Inputs (Consuming data)
#spring.cloud.stream.function.bindings.suggestTradeAdviceProcessor-in-0=input
#spring.cloud.stream.function.bindings.suggestTradeAdviceProcessor-out-0=output
spring.cloud.stream.bindings.suggestTradeAdviceProcessor-in-0.destination=stocks.news.analysis
spring.cloud.stream.bindings.suggestTradeAdviceProcessor-in-0.group=research-trader-agent
spring.cloud.stream.bindings.suggestTradeAdviceProcessor-out-0.destination=portfolio.trades


springdoc.swagger-ui.path=/swagger-ui.html

# For Outputs (Publishing data)
#spring.cloud.stream.bindings.suggestTradeAdviceProcessor-out-0.destination=<topic_or_exchange_name>