spring.application.name=portfolio-sql-analytics-mcp-server

spring.datasource.url=jdbc:postgresql://localhost:5432/postgresml
spring.datasource.username=postgresml
#spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver


#----------------------------
#spring.ai.mcp.server.enabled=true
#spring.ai.mcp.server.name=portfolio-sql-analytics-mcp-server
#spring.ai.mcp.server.version=0.0.1
#spring.ai.mcp.server.type=SYNC
#spring.ai.mcp.server.sse-endpoint=/sse
#spring.ai.mcp.server.sse-message-endpoint=/mcp/message

#spring.ai.mcp.server.protocol=STREAMABLE
server.port=9077
server.forward-headers-strategy=framework

springdoc.swagger-ui.servers-url=http://localhost:9077
#spring.ai.mcp.server.protocol.sse-endpoint=sse
#        instructions:
#spring.ai.mcp.server.stdio=false