spring.application.name=portfolio-agent-processor
server.port=8067


# Spring AI MCP Client
spring.ai.mcp.client.enable=true
spring.ai.mcp.client.name=portfolio-agent

app.portfolio.analytics.service.url=http://localhost:9077/analytics/asks

#spring.ai.mcp.client.toolcallback.enabled=false
#spring.ai.mcp.client.streamable-http.connections=sql
#spring.ai.mcp.client.streamable-http.connections.sql.url=http://localhost:9022
spring.ai.postgresml.embedding.enabled=false
logging.level.org.springframework.ai=DEBUG
logging.level.io.modelcontextprotocol=DEBUG

spring.rabbitmq.username=${TANZU_RABBITMQ_USER}
spring.rabbitmq.password=${TANZU_RABBITMQ_PASSWORD}

# 1. Force all consumers (queues) to use RabbitMQ Streams container
spring.cloud.stream.rabbit.default.consumer.containerType=stream
spring.datasource.url=jdbc:postgresql://localhost:5432/postgresml
spring.datasource.username=postgresml
#spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver








spring.cloud.function.definition=proposeTradeFunction
spring.cloud.function.web.path=/functions
spring.cloud.function.web.mappings.proposeTradeFunction.path=/functions/trades
spring.cloud.function.web.mappings.proposeTradeFunction.method=POST
spring.cloud.stream.http.POST=proposeTradeFunction
# For Inputs (Consuming data)
spring.cloud.stream.function.bindings.proposeTradeFunction-in-0=input
spring.cloud.stream.function.bindings.proposeTradeFunction-out-0=output
spring.cloud.stream.bindings.input.destination=portfolio.trades
spring.cloud.stream.bindings.input.group=processor

springdoc.swagger-ui.path=/swagger-ui.html

# For Outputs (Publishing data)
#spring.cloud.stream.bindings.proposeTradeFunction-out-0.destination=topic_or_exchange_name

spring.jpa.properties.hibernate.default_schema=portfolio
spring.liquibase.default-schema=portfolio
spring.liquibase.liquibase-schema=portfolio

# Automate table creation based on Java Entity classes
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=none

# Optional: Log the SQL commands in the console to see what Hibernate is doing
spring.jpa.show-sql=true
