spring.application.name=portfolio-agent-processor
server.port=8067


spring.datasource.url=jdbc:postgresql://localhost:5432/postgresml
spring.datasource.username=postgresml
#spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver


spring.ai.postgresml.embedding.enabled=false

spring.cloud.function.definition=proposeTradeFunction
spring.cloud.function.web.path=/functions
spring.cloud.function.web.mappings.proposeTradeFunction.path=/functions/trades
spring.cloud.function.web.mappings.proposeTradeFunction.method=POST
spring.cloud.stream.http.POST=proposeTradeFunction
# For Inputs (Consuming data)
spring.cloud.stream.function.bindings.proposeTradeFunction-in-0=input
spring.cloud.stream.function.bindings.proposeTradeFunction-out-0=output
spring.cloud.stream.bindings.input.destination=portfolio.trades
spring.cloud.stream.bindings.input.group=processor

springdoc.swagger-ui.path=/swagger-ui.html

# For Outputs (Publishing data)
spring.cloud.stream.bindings.proposeTradeFunction-out-0.destination=topic_or_exchange_name